version: "3"

services:
  app-ods: 
    build: .
    command: npm start
    ports:
      - "3001:3001"  
    volumes:
      - .:/usr/src/app
    depends_on:
      - database_mysql
  database_mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306"
